
'use strict';

/* ============================================================================
 * Hand-rolled QR Code encoder (ISO/IEC 18004, Model 2), byte mode only.
 * No external library. Implements: UTF-8 -> byte-mode segment -> pad ->
 * Reed-Solomon ECC (GF(256)) -> interleave -> matrix (finders/timing/
 * alignment/dark module/format+version info) -> zig-zag data placement ->
 * masking (8 candidates, 4 penalty rules, pick lowest).
 *
 * Every table/formula below was cross-checked against ISO/IEC 18004 Annex
 * tables (via Nayuki's MIT-licensed QR-Code-generator reference values and
 * thonky.com's published tutorial tables) and round-trip verified with an
 * independent jsQR decoder across all 40 versions x 4 EC levels before
 * shipping. See PLAN.md for the full derivation.
 * ==========================================================================*/

<<ct:inline logic.mjs>>
/* ============================================================================
 * Rendering: canvas, SVG, downloads
 * ==========================================================================*/

function renderToCanvas(canvas, matrixResult, options) {
  const { size, modules } = matrixResult;
  const { scale = 8, quietZone = 4, fg = '#000000', bg = '#ffffff' } = options || {};
  const total = size + quietZone * 2;
  canvas.width = total * scale;
  canvas.height = total * scale;
  const ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = fg;
  for (let r = 0; r < size; r++) {
    for (let c = 0; c < size; c++) {
      if (modules[r][c]) ctx.fillRect((c + quietZone) * scale, (r + quietZone) * scale, scale, scale);
    }
  }
}

// Repo/attribution constants shared by the PNG tEXt chunks (below) and the
// SVG metadata block, so both export paths agree on the exact same strings.
const TOOL_AUTHOR = 'claude tools';
const TOOL_REPO_URL = 'https://github.com/codercowboy/claude-tools';
const TOOL_SOFTWARE = 'claude-tools qr-generator';

// Embeds attribution metadata in the exported SVG: a leading XML comment
// (visible to anyone who opens the file as text) plus a Dublin-Core
// <metadata> block (machine-readable, standard SVG/XML practice) — same
// author + repo URL as the PNG's tEXt chunks. Purely additive markup; the
// visible <rect>/<path> geometry is unchanged, so the code stays crisp and
// scannable.
function toSVGString(matrixResult, options) {
  const { size, modules } = matrixResult;
  const { quietZone = 4, fg = '#000000', bg = '#ffffff' } = options || {};
  const total = size + quietZone * 2;
  let path = '';
  for (let r = 0; r < size; r++) {
    for (let c = 0; c < size; c++) {
      if (modules[r][c]) path += `M${c + quietZone},${r + quietZone}h1v1h-1z`;
    }
  }
  const comment = `<!-- Generated by ${TOOL_SOFTWARE} — ${TOOL_REPO_URL} -->`;
  const metadata =
    `<metadata><dc:creator>${TOOL_AUTHOR}</dc:creator><dc:source>${TOOL_REPO_URL}</dc:source></metadata>`;
  return (
    comment +
    `<svg xmlns="http://www.w3.org/2000/svg" xmlns:dc="http://purl.org/dc/elements/1.1/" viewBox="0 0 ${total} ${total}" width="${total * 8}" height="${total * 8}" shape-rendering="crispEdges">` +
    metadata +
    `<rect width="${total}" height="${total}" fill="${bg}"/>` +
    `<path d="${path}" fill="${fg}"/>` +
    `</svg>`
  );
}

/* ----------------------------------------------------------------------
 * Hand-rolled PNG tEXt-chunk injector (no library).
 *
 * canvas.toDataURL('image/png')/toBlob() produce a PNG with no custom
 * metadata — there's no browser API to add ancillary chunks. This parses
 * the PNG chunk stream (8-byte signature, then a sequence of
 * length(4 BE) + type(4 ASCII) + data(length) + CRC-32(4) chunks per the
 * PNG spec / ISO/IEC 15948) and inserts new tEXt chunks just before IEND.
 * Every other chunk — including IHDR and all IDAT (pixel) data — is copied
 * through byte-for-byte and never touched, so the rendered QR code's pixels
 * (and therefore its decodability) are completely unaffected; only chunk
 * framing is added.
 * ------------------------------------------------------------------- */

const PNG_SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

// Standard CRC-32 (ISO 3309 / ITU-T V.42), the exact algorithm the PNG spec
// requires for each chunk's trailing CRC. Shared impl: jbc-include/crc32.js,
// the crc32 export of the CtByteUtil module inlined ahead of this one.

// Builds one complete chunk (length + 4-char type + data + CRC) as bytes.
function buildPngChunk(type, data) {
  const out = new Uint8Array(12 + data.length);
  const view = new DataView(out.buffer);
  view.setUint32(0, data.length, false);
  for (let i = 0; i < 4; i++) out[4 + i] = type.charCodeAt(i);
  out.set(data, 8);
  view.setUint32(8 + data.length, crc32(out.subarray(4, 8 + data.length)), false);
  return out;
}

// tEXt chunk data = keyword (Latin-1, 1-79 chars) + 0x00 separator + text
// (Latin-1, uncompressed). Keywords/text used by this tool are known-good
// ASCII, so no further Latin-1 validation/escaping is needed here.
function buildTextChunk(keyword, text) {
  const data = new Uint8Array(keyword.length + 1 + text.length);
  for (let i = 0; i < keyword.length; i++) data[i] = keyword.charCodeAt(i) & 0xff;
  data[keyword.length] = 0x00;
  for (let i = 0; i < text.length; i++) data[keyword.length + 1 + i] = text.charCodeAt(i) & 0xff;
  return buildPngChunk('tEXt', data);
}

// Walks the chunk stream into { type, bytes } entries (bytes = the chunk's
// full length+type+data+crc span), so chunks can be reassembled verbatim.
function parsePngChunks(bytes) {
  for (let i = 0; i < 8; i++) {
    if (bytes[i] !== PNG_SIGNATURE[i]) throw new Error('not a PNG (bad signature)');
  }
  const chunks = [];
  let offset = 8;
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  while (offset < bytes.length) {
    const length = view.getUint32(offset, false);
    const type = String.fromCharCode(
      bytes[offset + 4], bytes[offset + 5], bytes[offset + 6], bytes[offset + 7],
    );
    const chunkEnd = offset + 12 + length;
    chunks.push({ type, bytes: bytes.subarray(offset, chunkEnd) });
    offset = chunkEnd;
  }
  return chunks;
}

// Returns a new PNG byte stream with tEXt chunks for each { keyword, text }
// entry inserted immediately before IEND. Throws if `pngBytes` doesn't look
// like a PNG or has no IEND — callers should catch and fall back to the
// original, unmodified bytes.
function injectPngTextChunks(pngBytes, entries) {
  const chunks = parsePngChunks(pngBytes);
  const iendIndex = chunks.findIndex((c) => c.type === 'IEND');
  if (iendIndex === -1) throw new Error('no IEND chunk found');
  const textChunks = entries.map(({ keyword, text }) => buildTextChunk(keyword, text));
  const totalLength =
    8 +
    chunks.reduce((sum, c) => sum + c.bytes.length, 0) +
    textChunks.reduce((sum, c) => sum + c.length, 0);
  const out = new Uint8Array(totalLength);
  out.set(PNG_SIGNATURE, 0);
  let pos = 8;
  for (let i = 0; i < iendIndex; i++) {
    out.set(chunks[i].bytes, pos);
    pos += chunks[i].bytes.length;
  }
  for (const tc of textChunks) {
    out.set(tc, pos);
    pos += tc.length;
  }
  out.set(chunks[iendIndex].bytes, pos);
  return out;
}

function dataUrlToBytes(dataUrl) {
  const binary = atob(dataUrl.split(',')[1]);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

// The metadata embedded in every downloaded PNG (Author + repo URL, plus a
// Software tag) — same attribution as the SVG export's <metadata> block.
const PNG_METADATA_ENTRIES = [
  { keyword: 'Author', text: TOOL_AUTHOR },
  { keyword: 'Source', text: TOOL_REPO_URL },
  { keyword: 'Software', text: TOOL_SOFTWARE },
];

// Takes a canvas's plain `toDataURL('image/png')` data URL and returns a
// same-content PNG data URL with the tEXt metadata chunks injected. Never
// throws: any failure anywhere in the injection falls back to returning the
// original, unmodified data URL, so a download can never break because of
// this best-effort enhancement.
function addPngMetadata(dataUrl) {
  try {
    const bytes = dataUrlToBytes(dataUrl);
    const withMetadata = injectPngTextChunks(bytes, PNG_METADATA_ENTRIES);
    let binary = '';
    for (let i = 0; i < withMetadata.length; i++) binary += String.fromCharCode(withMetadata[i]);
    return 'data:image/png;base64,' + btoa(binary);
  } catch (err) {
    return dataUrl;
  }
}

/* ============================================================================
 * Contrast check (WCAG relative luminance / contrast ratio)
 * ==========================================================================*/

function hexToRgb(hex) {
  const clean = hex.replace('#', '');
  const full = clean.length === 3 ? clean.split('').map((ch) => ch + ch).join('') : clean;
  const n = parseInt(full, 16);
  return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
}
function relLuminance(hex) {
  const { r, g, b } = hexToRgb(hex);
  const chan = (v) => {
    const s = v / 255;
    return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * chan(r) + 0.7152 * chan(g) + 0.0722 * chan(b);
}
function contrastRatio(hex1, hex2) {
  const l1 = relLuminance(hex1);
  const l2 = relLuminance(hex2);
  const lighter = Math.max(l1, l2);
  const darker = Math.min(l1, l2);
  return (lighter + 0.05) / (darker + 0.05);
}

/* ============================================================================
 * UI wiring
 * ==========================================================================*/

const inputEl = document.getElementById('qr-input');
const ecLevelEl = document.getElementById('ec-level-select');
const scaleEl = document.getElementById('scale-input');
const quietZoneEl = document.getElementById('quiet-zone-input');
const fgEl = document.getElementById('fg-color-input');
const bgEl = document.getElementById('bg-color-input');
const canvasEl = document.getElementById('qr-canvas');
const captionEl = document.getElementById('qr-caption');
const capacityHintEl = document.getElementById('capacity-hint');
const errorEl = document.getElementById('error-message');
const contrastWarningEl = document.getElementById('contrast-warning');
const downloadPngBtn = document.getElementById('download-png-btn');
const downloadSvgBtn = document.getElementById('download-svg-btn');
const copyInputBtn = document.querySelector('[data-testid="qr-input-copy"]');
const helpButtonEl = document.getElementById('help-button');
const helpOverlayEl = document.querySelector('[data-testid="help-overlay"]');
const helpDialogEl = document.querySelector('[data-testid="help-modal"]');
const helpCloseXEl = document.querySelector('[data-testid="help-modal"] [data-testid="modal-close-x"]');

let currentMatrix = null;

/* ============================================================================
 * Persistence: UI state (input + options) survives a reload via localStorage.
 * Namespaced, versioned key; best-effort — every read/write is wrapped in
 * try/catch and degrades silently, so the tool works fully with no stored
 * state (localStorage can be unavailable under file://, private mode, quota,
 * or browser policy). The rendered QR/canvas/matrix is DERIVED and is never
 * persisted — it's recomputed from the restored input+options on load.
 * ==========================================================================*/

const STORAGE_KEY = 'qr-generator:v1';
const HELP_SEEN_KEY = 'qr-generator:help-seen:v1';

function saveState() {
  try {
    localStorage.setItem(
      STORAGE_KEY,
      JSON.stringify({
        input: inputEl.value,
        ecLevel: ecLevelEl.value,
        scale: scaleEl.value,
        quietZone: quietZoneEl.value,
        fg: fgEl.value,
        bg: bgEl.value,
      }),
    );
  } catch (err) {
    // Best-effort: localStorage unavailable (file://, private mode, quota,
    // browser policy). Degrade silently to in-memory only.
  }
}

function loadState() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === 'object' ? parsed : null;
  } catch (err) {
    return null;
  }
}

// Applies stored state onto the live form fields, validating each field
// independently and falling back to the field's current markup default
// whenever a stored value is missing or malformed. Never touches the
// canvas/matrix (derived — re-rendered separately by the caller).
function applyStoredState() {
  const stored = loadState();
  if (!stored) return;
  if (typeof stored.input === 'string') inputEl.value = stored.input;
  if (typeof stored.ecLevel === 'string' && ['L', 'M', 'Q', 'H'].includes(stored.ecLevel)) {
    ecLevelEl.value = stored.ecLevel;
  }
  if (typeof stored.scale === 'string' || typeof stored.scale === 'number') {
    scaleEl.value = String(stored.scale);
  }
  if (typeof stored.quietZone === 'string' || typeof stored.quietZone === 'number') {
    quietZoneEl.value = String(stored.quietZone);
  }
  if (typeof stored.fg === 'string' && /^#[0-9a-fA-F]{6}$/.test(stored.fg)) fgEl.value = stored.fg;
  if (typeof stored.bg === 'string' && /^#[0-9a-fA-F]{6}$/.test(stored.bg)) bgEl.value = stored.bg;
}

// Whether the visitor has already dismissed the Help modal at least once.
// If localStorage throws/is unavailable, treat it as already-seen so we
// don't nag on every load — the least-annoying safe fallback (the ?
// button is always there if they want the modal later).
function hasSeenHelp() {
  try {
    return localStorage.getItem(HELP_SEEN_KEY) === '1';
  } catch (err) {
    return true;
  }
}

function markHelpSeen() {
  try {
    localStorage.setItem(HELP_SEEN_KEY, '1');
  } catch (err) {
    // Best-effort, same as saveState().
  }
}

function truncate(str, n) {
  return str.length > n ? str.slice(0, n - 1) + '…' : str;
}

function currentOptions() {
  return {
    scale: Math.max(1, Math.min(40, parseInt(scaleEl.value, 10) || 8)),
    quietZone: Math.max(0, Math.min(20, parseInt(quietZoneEl.value, 10) || 0)),
    fg: fgEl.value || '#000000',
    bg: bgEl.value || '#ffffff',
  };
}

function showError(message) {
  errorEl.textContent = message;
  errorEl.classList.add('visible');
}
function clearError() {
  errorEl.textContent = '';
  errorEl.classList.remove('visible');
}

function clearCanvas() {
  canvasEl.classList.add('hidden');
  const ctx = canvasEl.getContext('2d');
  ctx.clearRect(0, 0, canvasEl.width, canvasEl.height);
}

function disableDownloads() {
  downloadPngBtn.disabled = true;
  downloadSvgBtn.disabled = true;
}
function enableDownloads() {
  downloadPngBtn.disabled = false;
  downloadSvgBtn.disabled = false;
}

function updateContrastWarning() {
  const { fg, bg } = currentOptions();
  let ratio;
  try {
    ratio = contrastRatio(fg, bg);
  } catch {
    ratio = 21; // malformed color input — don't warn
  }
  if (ratio < 3) {
    contrastWarningEl.textContent = 'Low contrast between foreground and background — this code may not scan reliably.';
    contrastWarningEl.classList.add('visible');
  } else {
    contrastWarningEl.textContent = '';
    contrastWarningEl.classList.remove('visible');
  }
}

function doRender() {
  const text = inputEl.value;
  const ecLevel = ecLevelEl.value;
  clearError();
  updateContrastWarning();

  if (text.trim() === '') {
    clearCanvas();
    disableDownloads();
    captionEl.textContent = '';
    capacityHintEl.textContent = 'Enter text or a URL above to generate a QR code.';
    currentMatrix = null;
    return;
  }

  try {
    currentMatrix = encodeToMatrix(text, ecLevel);
  } catch (err) {
    clearCanvas();
    disableDownloads();
    showError(err.message);
    capacityHintEl.textContent = '';
    captionEl.textContent = '';
    currentMatrix = null;
    return;
  }

  canvasEl.classList.remove('hidden');
  renderToCanvas(canvasEl, currentMatrix, currentOptions());
  captionEl.textContent = `Version ${currentMatrix.version} · Level ${ecLevel}`;
  capacityHintEl.textContent = `Version ${currentMatrix.version} of 40 · Level ${ecLevel}`;
  canvasEl.setAttribute('aria-label', `QR code for: ${truncate(text, 60)}`);
  enableDownloads();
}

// In-field copy on the editable text/URL input: revealed only when the field
// is non-empty (CSS can't read a value, so the tool toggles [hidden]). The QR
// output is an image, so this input is the one copyable text value in the tool.
function syncCopyBtn() {
  if (copyInputBtn) copyInputBtn.hidden = inputEl.value.trim() === '';
}

if (copyInputBtn) {
  copyInputBtn.addEventListener('click', async () => {
    const text = inputEl.value;
    if (!text) return;
    const ok = await copy(text);
    if (!ok) return;
    flash(copyInputBtn, { label: '✅', revertTo: '📋' });
  });
}

// Shared trailing-edge debounce (jbc-include/util.js, inlined as a global).
const scheduleRender = debounce(doRender, 150);

[inputEl, ecLevelEl, scaleEl, quietZoneEl, fgEl, bgEl].forEach((el) => {
  el.addEventListener('input', () => {
    saveState();
    scheduleRender();
  });
});

// Keep the in-field copy button's visibility in sync with the input's value.
inputEl.addEventListener('input', syncCopyBtn);

downloadPngBtn.addEventListener('click', () => {
  if (!currentMatrix) return;
  const rawUrl = canvasEl.toDataURL('image/png');
  // Best-effort: embed Author/Source/Software tEXt metadata; addPngMetadata
  // never throws, so a bad injection just falls back to the plain PNG.
  const url = addPngMetadata(rawUrl);
  // addPngMetadata returns a PNG data URL (metadata-injected, or the original
  // on best-effort failure); decode it to bytes so the shared download helper
  // (jbc-include/util.js) can save the exact PNG content.
  const bytes = dataUrlToBytes(url);
  downloadBlob(new Blob([bytes], { type: 'image/png' }), `qr-code-v${currentMatrix.version}-${ecLevelEl.value}.png`);
});

downloadSvgBtn.addEventListener('click', () => {
  if (!currentMatrix) return;
  const svg = toSVGString(currentMatrix, currentOptions());
  const blob = new Blob([svg], { type: 'image/svg+xml' });
  // Shared download helper (jbc-include/util.js, inlined as a global).
  downloadBlob(blob, `qr-code-v${currentMatrix.version}-${ecLevelEl.value}.svg`);
});

/* ============================================================================
 * Help modal -- purely informational (what the tool does + how to use it),
 * so it's its own small dedicated dialog rather than confirmDialog (which is a
 * yes/no destructive-action confirm). Markup is static in the document
 * (shown/hidden via [hidden]) rather than built/torn down per open/close.
 * Structure/focus-handling mirrors tools/hat-picker and tools/color-designer
 * (see docs/conventions.md "First-load help popup (all tools)").
 * ==========================================================================*/

let helpPreviouslyFocused = null;

function getHelpFocusable() {
  return Array.from(
    helpDialogEl.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'),
  ).filter((el) => !el.disabled && el.getClientRects().length > 0);
}

function onHelpKeydown(e) {
  if (e.key === 'Escape') {
    e.preventDefault();
    closeHelp();
    return;
  }
  if (e.key !== 'Tab') return;
  const focusable = getHelpFocusable();
  if (focusable.length === 0) return;
  e.preventDefault();
  const idx = focusable.indexOf(document.activeElement);
  let next = e.shiftKey ? idx - 1 : idx + 1;
  if (next < 0) next = focusable.length - 1;
  if (next >= focusable.length) next = 0;
  focusable[next].focus();
}

function openHelp() {
  helpPreviouslyFocused = document.activeElement;
  helpOverlayEl.hidden = false;
  document.addEventListener('keydown', onHelpKeydown, true);
  helpDialogEl.scrollTop = 0;
  helpCloseXEl.focus({ preventScroll: true });
}

function closeHelp() {
  if (helpOverlayEl.hidden) return;
  helpOverlayEl.hidden = true;
  document.removeEventListener('keydown', onHelpKeydown, true);
  if (helpPreviouslyFocused && typeof helpPreviouslyFocused.focus === 'function') {
    try { helpPreviouslyFocused.focus(); } catch (err) { /* ignore */ }
  }
  helpPreviouslyFocused = null;
}

helpButtonEl.addEventListener('click', () => openHelp());
helpCloseXEl.addEventListener('click', () => closeHelp());
helpOverlayEl.addEventListener('mousedown', (e) => {
  if (e.target === helpOverlayEl) closeHelp();
});

// Restore persisted UI state (input + options) before the initial paint;
// best-effort — falls back to the markup defaults when there's nothing
// stored or it can't be read (see Persistence above). The canvas/matrix
// itself is never stored — this only re-renders it from restored inputs.
applyStoredState();

// Reflect the restored input value in the in-field copy button's visibility
// (applyStoredState sets .value directly, which fires no `input` event).
syncCopyBtn();

// Initial paint.
doRender();

// Auto-show the Help modal once, on a genuinely fresh visit only. Marking
// it seen right away (rather than on close) keeps this a true "once" --
// even if the visitor navigates away without explicitly closing it, it
// won't auto-show again next time.
if (!hasSeenHelp()) {
  markHelpSeen();
  openHelp();
}

/* ============================================================================
 * Testability: window.__qr namespace (inert for normal users)
 * ==========================================================================*/

window.__qr = {
  encodeToMatrix,
  utf8Bytes,
  charCountBits,
  selectVersion,
  getDataCodewordCount,
  getBlockPlan,
  getAlignmentPatternPositions,
  gfMul,
  rsGeneratorPoly,
  rsComputeRemainder,
  computeFormatBits,
  computeVersionBits,
  MASK_FNS,
  scorePenalty,
  renderToCanvas,
  toSVGString,
  crc32,
  buildPngChunk,
  buildTextChunk,
  parsePngChunks,
  injectPngTextChunks,
  addPngMetadata,
  PNG_METADATA_ENTRIES,
  TOOL_AUTHOR,
  TOOL_REPO_URL,
  TOOL_SOFTWARE,
  STORAGE_KEY,
  HELP_SEEN_KEY,
  hasSeenHelp,
  markHelpSeen,
  openHelp,
  closeHelp,
  syncCopyBtn,
  get currentMatrix() {
    return currentMatrix ? { ...currentMatrix, modules: currentMatrix.modules.map((r) => r.slice()) } : null;
  },
};
